### ISSUE TITLE
数据表配置保存后自动更改每页数量

### ISSUE THREAD

**Issue by 625412505** [nocobase/nocobase#395]
**Describe the bug**
数据表配置保存后自动更改每页数量，从50条/页变为10条/页

**Version**
v0.7.0-alpha.34+mysql 8.0

**To Reproduce**
1. 数据表配置
2. 创建数据表
3. 数据数据，提交

**Expected behavior**
每页数量保持不变

**Screenshots**
![image](https://user-images.githubusercontent.com/82276246/168468306-900ae0d1-ec1e-4b78-9bef-c5bee6f6af6b.png)
![image](https://user-images.githubusercontent.com/82276246/168468420-d7a904d2-6a03-48d0-8d31-a5140d2f7cdd.png)

**Comment by budnail** [comment]
Google Translation to English:
Title: Automatically change the quantity per page after the data table configuration is saved
After the data table configuration is saved, the number of each page is automatically changed, from 50 items/page to 10 items/page
Steps to reproduce the behavior:

> 1. data table configuration
> 2. Create data table
> 3. data data, submit

Expected behavior:
The number of pages per page remains the same

**Comment by 625412505** [comment]
v0.7.4-alpha.1 已修复
