### ISSUE TITLE
用creat-nocobase-app方式安装的 启动的时候报错 .env file stack=Error: Your database lower_case_table_names=1, please add DB_ UNDERSCORED=true，参数改成true后可以正常启动，但是还原备份的时候提示for use this backup file, please set DB_UNDERSCORED=false 

### ISSUE THREAD

**Issue by 0x22E09-8** [nocobase/nocobase#4863]
## * Describe the bug

用creat-nocobase-app方式安装的 启动的时候报错 .env file stack=Error: Your database lower_case_table_names=1, please add DB_ UNDERSCORED=true，参数改成true后可以正常启动，但是另外一台服务器还原备份的时候提示 for use this backup file, please set DB_UNDERSCORED=false 

## * Environment

- NocoBase version: 

- Database type and version: mysql-8.0.38-winx64
  

- OS:windows

- Deployment Methods:

- Docker image version:

- NodeJS version:

**Comment by hongboji** [comment]
1、The database lower_case_table_names=1 will lead to mandatory lowercase table names.
2, nocobase should set DB_ UNDERSCORED=true to work properly.
3、Recovering the backup file prompts the need to set DB_UNDERSCORED=false, because the backup file is backed up from the environment of DB_UNDERSCORED=false, and cannot be restored to the environment of DB_ UNDERSCORED=true.

To summarize, the reason for the problem is that the lower_case_table_names settings of the database lead to inconsistency between the backup file and the restored environment, so you need to set consistent parameters for the environment.

**Comment by hongboji** [comment]
This is not a bug, issues will be turned off

**Comment by 0x22E09-8** [comment]
> 1、The database lower_case_table_names=1 will lead to mandatory lowercase table names.1、数据库lower_case_table_names=1将导致强制小写表名。 2, nocobase should set DB_ UNDERSCORED=true to work properly.2、nocobase 应设置 DB_ UNDERSCORED=true 才能正常工作。 3、Recovering the backup file prompts the need to set DB_UNDERSCORED=false, because the backup file is backed up from the environment of DB_UNDERSCORED=false, and cannot be restored to the environment of DB_ UNDERSCORED=true.3、恢复备份文件提示需要设置 DB_UNDERSCORED=false，因为备份文件是从 DB_UNDERSCORED=false 的环境备份的，无法恢复到 DB_ UNDERSCORED=true 的环境。
> 
> To summarize, the reason for the problem is that the lower_case_table_names settings of the database lead to inconsistency between the backup file and the restored environment, so you need to set consistent parameters for the environment.综上所述，问题的原因是数据库的lower_case_table_names设置导致备份文件与恢复的环境不一致，因此需要为环境设置一致的参数。



> 份文件是从 DB_UNDERSCORED=false 的环境备份

备份环境是docker默认的 并不知道这个情况，所以如果想要正常恢复备份，是不是在备份环境中增加 DB_UNDERSCORED=true 这个参数就可以了 ，对原备份的文件使用有没有影响

**Comment by hongboji** [comment]
DB_UNDERSCORED belongs to the initialization parameter of NocoBase, and it is not allowed to be changed after use, because this parameter determines the case of the table name of the data table, and the history table created by the database will not be changed because of the change of DB_UNDERSCORED.

**Comment by hongboji** [comment]
The system built at the back adapts to the system at the front, while the parameters of the system at the front cannot be changed to adapt to the system at the back.
